### ISSUE TITLE
License Incompatibility

### ISSUE THREAD

**Issue by lleyton** [lunchcat/sif#27]
I recently stumbled across the project and became interested in packaging it. As such, I reviewed the licenses of the project and its dependencies, and noticed that [one of the dependencies pulled](https://github.com/lunchcat/sif/blob/235c8cc1a401a6004b9f5a49e024a00de88d9470/go.mod#L145) is [licensed under the GPL-2.0](https://github.com/projectdiscovery/ldapserver/blob/master/LICENSE), which is incompatible with the proprietary license of the project.

Note: The upstream project of that fork relicensed to MIT months ago, but the fork being pulled in is still GPL-2.0.

**Comment by vmfunc** [comment]
Hello, thanks for your concern. We're going to update ldapserver to upstream in order to fix those license inconsistencies

**Comment by vmfunc** [comment]
Feel free to reach out to us here or through Discord if you're still interested in packaging, or if you have any concerns.

**Comment by vmfunc** [comment]
Alright @lleyton, after a bit of research, here are my thoughts.

The GPL requires that any software it's included in must also be released under the GPL if distributed. However, if you're just using the GPL-licensed library internally without distributing it, you may not be bound by the GPL's requirements. Though, when you're using a library that has dependencies, like the MIT library (in our case, nuclei), that requires the GPL dependency, things can get more complicated, and we might have more leeway, as the dependency which requires ldapserver is itself, not compliant.

The license nuclei does have typically allows for more flexibility in how we can use and distribute the software. In our case, if the GPL-licensed dependency is only required by the MIT library and not directly by your proprietary software, hence we might be able to use it without violating the GPL, as long as we don't distribute the GPL-licensed code with our software, which we don't.

The key point here is whether your software forms a combined work with the GPL-licensed code. If it does, the GPL's copyleft provisions may apply to your entire software package. If it doesn't, and the GPL code is merely a separate part used indirectly, you might be able to argue that it doesn't affect the licensing of your proprietary software. 

References:

> "The licenses for most software are designed to take away your freedom to share and change it. By contrast, the GNU General Public License is intended to guarantee your freedom to share and change free software--to make sure the software is free for all its users." (GNU General Public License Version 2, Preamble)

> "Also, for each author's protection and ours, we want to make certain that everyone understands that there is no warranty for this free software." (GNU General Public License Version 2, Preamble)

> "You may modify your copy or copies of the Program or any portion of it, thus forming a work based on the Program, and copy and distribute such modifications or work under the terms of Section 1 above, provided that you also meet all of these conditions..." (GNU General Public License Version 2, Section 2)

> "If distribution of executable or object code is made by offering access to copy from a designated place, then offering equivalent access to copy the source code from the same place counts as distribution of the source code, even though third parties are not compelled to copy the source along with the object code." (GNU General Public License Version 2, Section 3)

Waiting for your input on this.

**Comment by tessa-u-k** [comment]
as discussed in discord this is not a direct violation by lunchcat but by [nuclei,](https://github.com/projectdiscovery/nuclei) its not currently in the cards for us to maintain a library or find a replacement.
